name: 'Summarize Commit Stage'
description: 'Generate a comprehensive summary of the commit stage results including build status and Docker image information'
author: 'Optivem'

inputs:
  stage-result:
    description: 'Result of the stage job (success, failure, cancelled, etc.)'
    required: true
  stage-name:
    description: 'Name of the stage being summarized'
    required: false
    default: 'Commit Stage'
  component-name:
    description: 'Name of the component being processed (e.g., Monolith, API, Frontend)'
    required: true
  image-url:
    description: 'Full URL of the pushed Docker image'
    required: true
  image-digest-url:
    description: 'Full URL with SHA256 digest of the pushed image'
    required: true
  image-created:
    description: 'Timestamp when the Docker image was created'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Generate Commit Stage Summary
      uses: optivem/summarize-stage-action@v1
      with:
        stage-result: ${{ inputs.stage-result }}
        stage-name: '${{ inputs.stage-name }} - ${{ inputs.component-name }}'
        stage-success-message: 'Successfully Published Docker Image:'
        stage-success-content: |
          **Image URL:**
          `${{ inputs.image-url }}`
          
          **Image Created:**
          `${{ inputs.image-created }}`
          
          **Image Digest URL:**
          `${{ inputs.image-digest-url }}`
          
          ⚠️ *If digest URL appears truncated, check 'Publish Docker Image' step logs for full details*